# Activate with: --spring.profiles.active=postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/linkforge
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.h2.console.enabled=false
